Update README and makefile to reflect new changes
  - Remove old TODOs from the README file. Makefile has been created.
  - Better naming of the older compile target of the makefile. Calling it lint,
    and update the dependency of this target.

diff --git a/projects/base1-cluster/makefile b/projects/base1-cluster/makefile
--- a/projects/base1-cluster/makefile
+++ b/projects/base1-cluster/makefile
@@ -9,12 +9,12 @@ build: init
 init:
 	mkdir -p ${BUILD_DEST}
 
-export:
+export:  build
 	rsync -auvz ${BUILD_DEST}/code ansible@10.4.14.101:/home/ansible/
 
-compile:
+lint: build
 	ansible-playbook -i ./build/code/hosts --syntax-check --list-tasks ./build/code/site.yml; \
-	if [ $$? -eq 0 ] ; then echo "no compilation errors" ; fi
+	if [ $$? -eq 0 ] ; then echo "No syntax errors in ansible scripts." ; fi
 
 clean:
 	rm -rf ${BUILD_DEST}
